### PR TITLE
Add Code Geass character reading a Java book

### PR DESCRIPTION
**Pull request by g-n-x**
Added the character CC reading a Java book to the Java folder.

### CODE REVIEW

**Comment by Asday** [comment]
Oh so _that's_ what C.C. stands for.

**Comment by kotx** [comment]
> Oh so _that's_ what C.C. stands for.

hm?

**Comment by Asday** [comment]
"Codegeass Character".

**Comment by kotx** [comment]
> "Codegeass Character".

noooo

**Pull request merged**
