### PR TITLE
Love Live girls

### PR DESCRIPTION
**Pull request by zbigos**

### CODE REVIEW

**Comment by Akaricchi** [comment]
In case you want to change the filename, that's Maki Nishikino and Nico Yazawa from left to right.

**Comment by zbigos** [comment]
I don't know if there is a standard for naming files with multiple characters. If there is, I can change it's name (naming it by the anime makes the filename shorter)

**Comment by ouuan** [comment]
I prefer naming it with the character's name.

**Comment by ouuan** [comment]
BTW, "μ's" is shorter and better than "Love Live".

**Comment by Asday** [comment]
Yeah but I have no idea how to type that.

**Comment by ouuan** [comment]
> Yeah but I have no idea how to type that.

So "Maki and Nico" is fine.

**Comment by bucket3432** [comment]
I'd stick with ASCII characters in filenames for simplicity, so no "µ's".

**Pull request merged**
