### PR TITLE
Create Ethereum

### PR DESCRIPTION
**Pull request by Riely007**
Want to add an anime girl holding Mastering Ethereum book pic :)

### CODE REVIEW

**Comment by Animenosekai** [comment]
I think you need to upload an image with an anime girl holding "Mastering Ethereum"

**Comment by Asday** [comment]
Even if this was a picture of an anime girl doing something related to ethereum, :-1: on the grounds of it being ethereum.

**Comment by laynH** [comment]
You know what I'm just going to make the rule that we aren't doing crypto in this repo. Also your PR is broken you forgot to commit the image file or something.

**Comment by Asday** [comment]
> I'm just going to make the rule that we aren't doing crypto in this repo.

Fucking KING.

**Pull request closed without merging**
