### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by chriskuech**
Added a CC0 license

### CODE REVIEW

**Comment by chriskuech** [comment]
https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/issues/64

**Comment by Asday** [comment]
Not sure CC0 is appropriate, as the majority of the images are modifications of copyrighted work.  Perhaps WTFPL?

**Comment by chriskuech** [comment]
ok.  Here's a WTFPL:

```
            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                    Version 2, December 2004

 Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>

 Everyone is permitted to copy and distribute verbatim or modified
 copies of this license document, and changing it is allowed as long
 as the name is changed.

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. You just DO WHAT THE FUCK YOU WANT TO.
```

What should I put for the copyright?

**Comment by bucket3432** [comment]
IANAL, but I don't think you can legally put such a lax license on this repo because none of us hold the copyrights for the original works. The derivative works here fall under "fair use", if even that.

**Comment by Asday** [comment]
This would be an interesting case, as the first factor of fair use is highly questionable herein.

It would be very easy to argue that any one picture photoshopped to have a programming book instead of whatever was originally in frame is not transformative, unless the image is making a greater point.

That this is a large collection of such photoshops, though, from _disparate_ copyright holders, there's a counterargument that the collection lends transformativity.

Hence me initially saying I don't think CC0 is appropriate.  CC0 waives all copyright on the licensed content, but whether the copyright on the licensed content is ours to waive is as described above.  Far more appropriate is the WTFPL, which better reflects the spirit in which the collection has been undertaken, and the legal strength any license would have.

Of course, that doesn't solve #64, but I don't think anything will.  Copyright "trolls", or "holders", depending on one's perspective, will trample whatever license there is, and github will likely roll over to a DMCA request similarly.

**Comment by bucket3432** [comment]
Agreed, if we were to slap a licence on this, I would vote for the WTFPL.

**Comment by ritiek** [comment]
I'll probably be OK with any sane license (CC0 or WTFPL are all good). But, I don't know if this holds true here but wouldn't all the contributors have to agree to license their (modified?) work under whatever the new license is before we can change the license of the repository?

**Comment by bucket3432** [comment]
Technically, yes, we're supposed to get the permission from _all_ the contributors (and maybe even the creators of the original modified images) to change the licence. I don't expect anyone to have a problem with slapping on such a licence given the nature of this collection, but that's what we would have to do if we were following the rules.

**Comment by chriskuech** [comment]
_Creating_ a meme, such as anime girls holding programming books, is legal under parody law.  I'm not sure _using_ someone else's meme is protected unless expressly permitted.   Therefore by adding a free use license, we should be good.  The only remaining concern would be around if someone adds a meme they did not create.

**Comment by Asday** [comment]
Simply describing something as, or transforming something into, a meme doesn't exempt it from copyright law.  Were uploading feature-length films to youtube with the wilhelm scream editied in at some hidden point to become a meme, that wouldn't make the uploaders free from liability.

**Comment by windowsEmmie** [comment]
I'm not seeing the reasoning for attaching a license to the repo. It's not really an official project so much as its a place to hold on to images that originate on varied imageboards - I'm not sure how much content on here is OC, but right now I have my doubts about copyright complaints over the edits posted here.

I would back adding something to the README, and keeping things largely as is, but otherwise I don't see why we should fix something that doesn't seem to be broken.

**Comment by chriskuech** [comment]
To be clear, this isn't for the safety of the repo, this is for the safety of others referencing the repo.  What good is a central repository if people aren't allowed to use things in the repository?  It would be cool to use these in knowledge sharing articles.  Unfortunately, unless you fork out hosting costs, you are posting to a proprietary platform and therefore arguably the images need a license allowing commercial use, even if the writer isn't really profiting.

**Comment by boyEstrogen** [comment]
As some people on here have already said most of these images are edits of existing copyrighted media, id rather not put a licence on any off since I don't want to risk upsetting anyone who either made the edits or owns the original media.

I would like to make sure that people know its ok to copy this repo and make changes to it in what ever way they see fit but i dont want to claim ownership of any of the images. If there is some way to claim ownership of the directory structure or something and then give people the right to copy and modify the repo how ever they want I'd like to do that.

**Comment by tpenguinltg** [comment]
> I would like to make sure that people know its ok to copy this repo and make changes to it in what ever way they see fit but i dont want to claim ownership of any of the images. If there is some way to claim ownership of the directory structure or something and then give people the right to copy and modify the repo how ever they want I'd like to do that.

The problem is, the proper way to do that _is_ a license. Copyright covers the right to distribute the work, but unless you claim ownership of the images or are permitted to distribute by another license, you can't technically slap a license on it permitting the redistribution of the images. That's why I suggested putting an informal note in the README: it expresses your intentions without being legally binding (probably).

**Comment by Asday** [comment]
>(probably)

Herein lies the promble.  None of us are lawyers.  Either we hire one to do it properly, we put something whimsical up like the WTFPL, or we don't do anything.

Trying to do it properly ourselves is folly.

**Comment by TobiX** [comment]
The right license for such content is CC-0. It's not part of the short deed, but the full license text clearly states under 4c:

> Affirmer disclaims responsibility for clearing rights of other persons that may apply to the Work or any use thereof, including without limitation any person's Copyright and Related Rights in the Work. Further, Affirmer disclaims responsibility for obtaining any necessary consents, permissions or other rights required for any use of the Work.

Therefore, CC-0 clearly states that YOU don't claim any copyright over the images in this repository, but you don't know or care the copyright state of the original work.

(IANAL and such, but exactly this part makes CC-0 quite unusable in big companies)

**Comment by bucket3432** [comment]
Again, IANAL, but the intent of CC0 is to release it in the public domain, with some clauses to emulate the public domain in jurisdictions that don't have such a concept. But that only applies if we own the copyright to the work in question. The images in this repo are not original works: they are derivative works of copyrighted works that we may or may not have had the permission to produce. If they were original, then sure, CC0 may be appropriate. Even if we suppose that it is within our legal rights to be able to produce the content, it would be at minimum irresponsible because CC0 would grant rights that were not given by the original copyright _and_ it's irrevocable.

**Pull request closed without merging**
