### PR TITLE
Adding new hololive eng vtuber Ninomae Ina'nis holding eloquent javascript

### PR DESCRIPTION
**Pull request by alstrash**
Heyo, just adding a vtuber here, I believe we need more vtubers holding programming books. 
Cheers 🍣.
Ninomae_Ina'nis_Holding_Eloquent_Javascript

### CODE REVIEW

**Comment by Asday** [comment]
And what a VTuber.

**Comment by alstrash** [comment]
Yeah, she seems like she could kill you but is a snowflake.

**Comment by laynH** [comment]
merged. also very cute touhou

**Comment by alstrash** [comment]
Nice

**Pull request merged**
