### PR TITLE
Adds Hanabi Yasuraoka from Kuzu no Honkai reading a CSharp book

### PR DESCRIPTION
**Pull request by SweptWasTaken**
I made this and thought it'd be good here.

Yasuraoka_Hanabi_Reading_CSharp_Language_Book png

### CODE REVIEW

**Comment by rosenishere** [comment]
Big fat agree
agree agree agree
**agree I agree**

**Comment by CsarChvz** [comment]
Good!

**Comment by rosenishere** [comment]
C# Big Money

**Comment by rosenishere** [comment]
check the patch's pull request I fixed bug
**e**

**Pull request merged**
